version: '3.8'

services:
  # 1. Database
  mysql-db:
    image: mysql:8.0
    container_name: lettre_mysql_container
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=lettre_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Backend (Node.js)
  app:
    build: .
    container_name: lettre_backend_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=mysql://root@mysql-db:3306/lettre_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  # 3. phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: lettre_phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - "8080:80"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - app-network


  # 4. Prisma Studio
  prisma-studio:
    build: .
    container_name: lettre_prisma_studio
    command: npx prisma studio --browser none
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=mysql://root@mysql-db:3306/lettre_db
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
